apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: localstack
    io.kompose.service: localstack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ .Release.Name }}-ingress
  namespace: localstack
spec:
  ingressClassName: {{ .Release.Name }}-ingress
  rules:
    - host: www.localstack-web.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localstack
                port:
                  number: 4566

