apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: localstack
    io.kompose.service: localstack
  annotations:
    kompose.cmd: kompose -f docker-compose.localstack.yml convert -c
    kompose.version: 1.21.0 (992df58d8)

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: localstack-web
      io.kompose.service: localstack
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: localstack-web
        io.kompose.service: localstack
    spec:
{{/*      affinity: { { .Values.affinity | toJson } }*/}}
      containers:
        - name: webserver
          image: "nginx:latest"
          ports:
            - name: webserver
              containerPort: 80
          resources:
            requests:
              memory: 500Mi
              cpu: 100m
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5

